# Generated by Django 6.0.3 on 2026-03-06 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('slug_convocacao', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('mensagem_boas_vindas', models.TextField(blank=True, help_text='Ex: Sejam bem-vindos a Assembleia Geral do Condomínio Madri III', null=True)),
                ('link_termos', models.URLField(blank=True, help_text='Link para visualização dos termos/edital', max_length=500, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('is_ativo', models.BooleanField(default=True)),
                ('mostrar_fotos', models.BooleanField(default=True, verbose_name='Mostrar fotos na urna?')),
            ],
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo do Cliente (URL)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Assembleia Condominial, Eleição Sindical', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('exige_aprovacao_cadastro', models.BooleanField(default=True)),
                ('voto_com_peso', models.BooleanField(default=False, help_text='Habilita contagem por fração ideal/cotas')),
                ('permite_procuracao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Aprovação de Contas 2025', max_length=255)),
                ('tipo_enquete', models.CharField(choices=[('candidatos', 'Eleição de Candidatos/Chapas'), ('aprovacao', 'Aprovação (Sim / Não / Abster)')], default='candidatos', max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_votacao', 'Em Votação'), ('encerrada', 'Encerrada')], default='aguardando', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to='votacao.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto (URL)')),
                ('enquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='votacao.enquete')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='votacao.organizacao'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='votacao.tipoevento'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('enquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votacao.enquete')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.opcao')),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('peso_voto', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado (Link Enviado)'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_utilizado', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleitores', to='votacao.evento')),
            ],
            options={
                'unique_together': {('evento', 'cpf')},
            },
        ),
    ]
