# Generated by Django 5.0.2 on 2026-02-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='mostrar_fotos',
            field=models.BooleanField(default=True, verbose_name='Mostrar fotos dos candidatos na urna?'),
        ),
        migrations.AddField(
            model_name='opcao',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto do Candidato (URL)'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo do Cliente (URL)'),
        ),
    ]
